apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260527-210237-3y5yzscwc97c-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260527-210237-3y5yzscwc97c.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260527-210237-3y5yzscwc97c-service
            port:
              number: 80
